### PR TITLE
add underline for hovered top 20 links

### PR DESCRIPTION
**Pull request by stvnrlly**
This makes the fact that the page titles are links a little more obvious.

### CODE REVIEW

**Comment by konklone** [comment]
Mind throwing in a screenshot of the effect?

**Comment by stvnrlly** [comment]
screen shot 2015-04-21 at 11 44 58 pm

**Comment by cew821** [comment]
I am :+1: to this.

**Comment by konklone** [comment]
Thanks, @stvnrlly! =)

**Pull request merged**
