### PR TITLE
Losslessly compress images

### PR DESCRIPTION
**Pull request by waldoj**
Recompressed all images with ImageOptim, and optimized PNG transparency
with ImageAlpha, resulting in much smaller files.

`share-image.png`: 68 kb → 56 kb
`usa_gov_logo.png`: 7 kb → 4 kb
`usa_gov_logo_white.png`: 14 kb → 3 kb

### CODE REVIEW

**Comment by konklone** [comment]
You're a champ.

**Comment by leahbannon** [comment]
:heart:

**Comment by waldoj** [comment]
I'm a one-trick pony, when it comes to 18F repositories. Clone repo, drop images on ImageOptim, file pull request. I figure if I do it often enough, y'all will start doing it yourselves. :)

**Comment by gbinal** [comment]
Thanks, @waldoj - Taking that to heart, posting in team chat.  :)

**Pull request merged**
