### PR TITLE
Removing blue outline from bars in chart on click

### PR DESCRIPTION
**Pull request by bchartoff**
Not sure if this is a feature or a bug, but I find it a bit distracting.

### CODE REVIEW

**Comment by konklone** [comment]
The effect @bchartoff is talking about:

image

I agree. @shawnbot @smarina04 @tdlowden ?

**Comment by smarina04** [comment]
I'm fine with the change.

**Comment by tdlowden** [comment]
+1

**Comment by bchartoff** [comment]
Great! Made change in the Sass with PR #194

**Pull request merged**
