### PR TITLE
lightening up the grey borders

### PR DESCRIPTION
**Pull request by rypan**
going from `#aaa` to `#E4E4E4`

### CODE REVIEW

**Comment by cew821** [comment]
This should be done in the .scss file... also I think that might be too light? Maybe something more like #ccc?

**Comment by cew821** [comment]
or maybe #ddd

**Comment by konklone** [comment]
#ddd is so close to #e4e4e4 as to make no difference, I can barely make out the difference when I compare. #ccc is discernibly in-between.

I updated the branch to make the change to #e4e4e4 in the sass file. I'll leave it to others to change or merge.

**Comment by konklone** [comment]
Or, hmm, this is a fork, so I can't update the branch. I've just gone ahead and merged it. @cew821 I also think #ccc might be better, but no strong feelings here.

**Pull request merged**
